# Generated by Django 5.0.1 on 2024-01-04 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unityofconsumption',
            name='is_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unityofconsumption',
            name='is_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unityofconsumption',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uc', to='client.house'),
        ),
    ]
