# Generated by Django 5.0.1 on 2024-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_unityofconsumption_is_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unityofconsumption',
            name='energy_suppliers',
            field=models.ManyToManyField(blank=True, related_name='energy_recipients', to='client.unityofconsumption'),
        ),
    ]
